{
 "title": "Docker stats",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Running containers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "running_containers", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Stopped containers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "stopped_containers", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total images",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "total_images", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Container Network - Bytes Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total[1m]) / (1024*1024)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container Network - Bytes Transmitted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total[1m]) / (1024*1024)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total[1m]) / 1024 / 1024",
     "legendFormat": "{{device}} - read"
    },
    {
     "expr": "rate(node_disk_written_bytes_total[1m]) / 1024 / 1024",
     "legendFormat": "{{device}} - write"
    }
   ]
  },
  {
   "title": "Container CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total[1m]) * 100",
     "legendFormat": "{{container_label_com_docker_compose_service}}"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(container_memory_usage_bytes / 256 / 1024 / 1024) * 100",
     "legendFormat": "{{container_label_com_docker_compose_service}}"
    }
   ]
  }
 ]
}